import fs from "fs";
import path from "path";
import { logger } from "@/lib/logger";

export async function sendEmail({
  to,
  subject,
  html,
}: {
  to: string;
  subject: string;
  html: string;
}) {
  logger.info(`Sending email to ${to} with subject "${subject}"`);

  // Local Fallback: Write HTML file under tmp/sent-emails/
  try {
    const dirPath = path.join(process.cwd(), "tmp", "sent-emails");
    if (!fs.existsSync(dirPath)) {
      fs.mkdirSync(dirPath, { recursive: true });
    }

    // Safe filename mapping
    const safeTo = to.replace(/[^a-zA-Z0-9@]/g, "-");
    const safeSubject = subject.replace(/[^a-zA-Z0-9]/g, "-").slice(0, 30);
    const filename = `${Date.now()}_${safeTo}_${safeSubject}.html`;
    const filePath = path.join(dirPath, filename);

    // Beautiful HTML envelope wrap for standard look
    const fullHtml = `
      <!DOCTYPE html>
      <html>
        <head>
          <meta charset="utf-8">
          <title>${subject}</title>
        </head>
        <body style="margin: 0; padding: 0; background-color: #0f0f11; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; color: #ededef;">
          <table width="100%" cellpadding="0" cellspacing="0" style="background-color: #0f0f11; padding: 40px 20px;">
            <tr>
              <td align="center">
                <table width="100%" max-width="600" style="max-width: 600px; width: 100%; border: 1px border #27272a; background-color: #18181b; padding: 24px; border-collapse: collapse;">
                  <!-- Header -->
                  <tr>
                    <td style="padding-bottom: 20px; border-b: 1px solid #27272a;">
                      <span style="font-size: 16px; font-weight: bold; letter-spacing: 0.05em; color: #ffffff;">TRANSITOPS</span>
                      <span style="font-size: 12px; color: #a1a1aa; float: right; padding-top: 4px;">SYSTEM ALERT</span>
                    </td>
                  </tr>
                  <!-- Body -->
                  <tr>
                    <td style="padding-top: 24px;">
                      ${html}
                    </td>
                  </tr>
                  <!-- Footer -->
                  <tr>
                    <td style="padding-top: 32px; border-t: 1px solid #27272a; font-size: 10px; color: #71717a; text-align: center; line-height: 1.5;">
                      This is an automated operational alert generated by the TransitOps fleet portal.<br />
                      Depot: Gandhinagar Depot GJ-14
                    </td>
                  </tr>
                </table>
              </td>
            </tr>
          </table>
        </body>
      </html>
    `;

    fs.writeFileSync(filePath, fullHtml, "utf-8");
    logger.info(`DX Email Fallback: Saved email markup to ${filePath}`);
  } catch (err) {
    logger.error("Failed to save email copy to tmp directory", err);
  }
}
